 export const resList = [
 
        {
          info: {
            id: "1125473",
            name: "McDonald's",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2026/6/18/a35398d6-c1d8-4593-b1ce-0c522da671f6_1125473.JPG",
            locality: "Gandipet Mandal",
            areaName: "Manikonda Jagir Village",
            costForTwo: "₹400 for two",
            cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
            avgRating: 4.2,
            parentId: "630",
            avgRatingString: "4.2",
            totalRatingsString: "1.9K+",
          },
        },
        {
          "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
          info: {
            id: "111504",
            name: "NIC Ice Creams",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2026/7/16/0d23c755-c641-47c9-94f6-affa73a833c0_111504.JPG",
            locality: "OU Colony Manikonda",
            areaName: "Shaikpet",
            costForTwo: "₹120 for two",
            cuisines: ["Ice Cream", "Desserts"],
            avgRating: 4.5,
            veg: true,
            parentId: "6249",
            avgRatingString: "4.5",
            totalRatingsString: "17K+",
          },
        },
        {
          info: {
            id: "620620",
            name: "Agra Sweets Banjara",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2026/9/13/635e93bf-a5ef-4e83-bdec-49dcfd663254_620620.jpg",
            locality: "Rahul Colony",
            areaName: "Tolichowki",
            costForTwo: "₹250 for two",
            cuisines: ["Sweets", "Desserts", "Chaat", "Snacks", "Beverages"],
            avgRating: 4.4,
            veg: true,
            parentId: "34",
            avgRatingString: "4.4",
            totalRatingsString: "6.7K+",
          },
        },
        {
          info: {
            id: "240185",
            name: "Burger King",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/bced9b52-f88c-4869-93f9-bafb284d7f83_240185.jpg",
            locality: "Sheikpet",
            areaName: "Toli Chowki",
            costForTwo: "₹350 for two",
            cuisines: ["Burgers", "American"],
            avgRating: 4.2,
            parentId: "166",
            avgRatingString: "4.2",
            totalRatingsString: "43K+",
          },
        },
        {
          info: {
            id: "514120",
            name: "The Shawarma Kingdom",
            cloudinaryImageId: "qjx1dodveggwhk5fxis6",
            locality: "Ou Colony Shaikpet",
            areaName: "Manikonda",
            costForTwo: "₹220 for two",
            cuisines: ["Lebanese", "Snacks"],
            avgRating: 4.2,
            parentId: "307310",
            avgRatingString: "4.2",
            totalRatingsString: "770",
          },
        },
        {
          info: {
            id: "1034906",
            name: "Alanati",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/27/60f31935-0621-4cbc-ba4d-1bf26be61a48_1034906.JPG",
            locality: "ABINANDANA SHIKAR",
            areaName: "Manikonda",
            costForTwo: "₹800 for two",
            cuisines: ["Chinese"],
            avgRating: 4.3,
            parentId: "420111",
            avgRatingString: "4.3",
            totalRatingsString: "1.6K+",
          },
        },
        {
          info: {
            id: "1061328",
            name: "Crimson Chopsticks",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2025/3/27/8bb74c38-ebec-458b-8781-a457ab7d186f_1061328 (1).jpg",
            locality: "Jubilee Hills",
            areaName: "Jubilee Hills",
            costForTwo: "₹400 for two",
            cuisines: ["Chinese", "Asian", "Fast Food", "Thai", "Hyderabadi"],
            avgRating: 4,
            parentId: "616251",
            avgRatingString: "4.0",
            totalRatingsString: "1.7K+",
          },
        },
        {
          info: {
            id: "1037718",
            name: "Biryani Souq",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2025/2/4/ba813b8e-d3df-4ec7-9a1d-668abd805784_1037718.sss.jpg",
            locality: "Jubilee Hills",
            areaName: "Jubilee Hills",
            costForTwo: "₹600 for two",
            cuisines: [
              "Biryani",
              "Hyderabadi",
              "Kebabs",
              "North Indian",
              "Tandoor",
              "Starters",
            ],
            avgRating: 4.1,
            parentId: "603972",
            avgRatingString: "4.1",
            totalRatingsString: "4.1K+",
          },
        },
        {
          info: {
            id: "484589",
            name: "KFC",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2026/7/1/3be44c7c-209e-4d2c-9e2e-d520f1fa880f_484589.JPG",
            locality: "Manikonda Main Road",
            areaName: "Manikonda",
            costForTwo: "₹400 for two",
            cuisines: ["Burgers", "Fast Food", "Rolls & Wraps"],
            avgRating: 3.7,
            parentId: "547",
            avgRatingString: "3.7",
            totalRatingsString: "10K+",
          },
        },
        {
          info: {
            id: "340856",
            name: "Pizza Hut",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2026/6/15/b470d602-782a-4c2b-9c10-76f20e4094f6_340856.JPG",
            locality: "Toli Chowki",
            areaName: "Tolichowki",
            costForTwo: "₹350 for two",
            cuisines: ["Pizzas"],
            avgRating: 4.3,
            parentId: "721",
            avgRatingString: "4.3",
            totalRatingsString: "8.5K+",
          },
        },
        {
          info: {
            id: "413320",
            name: "The Belgian Waffle Co.",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/16/63077393-e259-4dbf-8613-d2061eca4e3e_413320.jpg",
            locality: "OU Colony",
            areaName: "Manikonda",
            costForTwo: "₹200 for two",
            cuisines: ["Desserts", "Waffle", "Coffee"],
            avgRating: 4.2,
            veg: true,
            parentId: "2233",
            avgRatingString: "4.2",
            totalRatingsString: "4.6K+",
          },
        },
        {
          info: {
            id: "68331",
            name: "Sweet Truth - Cake and Desserts",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2026/2/24/1819aa62-ce79-4bef-bca1-b3ea9cc7e571_68331.JPG",
            locality:
              "First Floor, Shaikpet Village, beside Thick shake factory",
            areaName: "Shaikpet",
            costForTwo: "₹450 for two",
            cuisines: ["Desserts", "Ice Cream", "Bakery", "Beverages"],
            avgRating: 3.8,
            parentId: "4444",
            avgRatingString: "3.8",
            totalRatingsString: "1.7K+",
          },
        },
        {
          info: {
            id: "2498",
            name: "Vasista's Srilakshmi",
            cloudinaryImageId: "gk9lfkobvwgurghaevbn",
            locality: "Manikonda",
            areaName: "Shaikpet",
            costForTwo: "₹350 for two",
            cuisines: [
              "Biryani",
              "Chinese",
              "South Indian",
              "Andhra",
              "Tandoori",
              "Seafood",
              "Desserts",
              "Snacks",
            ],
            avgRating: 4.2,
            parentId: "387872",
            avgRatingString: "4.2",
            totalRatingsString: "222K+",
          },
        },
        {
          info: {
            id: "335331",
            name: "Natural Ice Cream",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2025/3/21/0cf8ec80-771a-49c8-bff4-f84732117d20_335331.jpg",
            locality: "Manikonda",
            areaName: "Shaikpet",
            costForTwo: "₹150 for two",
            cuisines: ["Ice Cream", "Desserts"],
            avgRating: 4.6,
            veg: true,
            parentId: "2093",
            avgRatingString: "4.6",
            totalRatingsString: "4.0K+",
          },
        },
        {
          info: {
            id: "68326",
            name: "Faasos - Wraps, Rolls & Shawarma",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/28/b5cce774-b3d6-4e7d-88f2-b860a31db655_68326.JPG",
            locality:
              "First Floor, Shaikpet Village, beside Thick shake factory",
            areaName: "Shaikpet",
            costForTwo: "₹200 for two",
            cuisines: [
              "Wraps",
              "rolls",
              "Fast Food",
              "Burger",
              "shawarma",
              "Rice Bowls",
            ],
            avgRating: 4,
            parentId: "21809",
            avgRatingString: "4.0",
            totalRatingsString: "12K+",
          },
        },
        {
          info: {
            id: "9538",
            name: "Karachi Bakery",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2026/9/26/e1d82773-5716-498a-8370-565635138651_9538.jpg",
            locality: "Tolichowki",
            areaName: "Shaikpet",
            costForTwo: "₹200 for two",
            cuisines: [
              "Bakery",
              "Pizzas",
              "Snacks",
              "Chinese",
              "Italian",
              "American",
              "Desserts",
              "Sweets",
            ],
            avgRating: 4.5,
            parentId: "1262",
            avgRatingString: "4.5",
            totalRatingsString: "23K+",
          },
        },
        {
          info: {
            id: "541933",
            name: "Great Indian Khichdi by EatFit",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2026/1/21/89cda866-88f1-44d8-859b-33fbf9f527cd_541933.JPG",
            locality: "Beside KFC",
            areaName: "Manikonda",
            costForTwo: "₹200 for two",
            cuisines: ["Indian", "Home Food", "Healthy Food", "Snacks"],
            avgRating: 3.8,
            veg: true,
            parentId: "319582",
            avgRatingString: "3.8",
            totalRatingsString: "2.4K+",
          },
        },
        {
          info: {
            id: "68328",
            name: "Oven Story Pizza",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2025/5/29/1f2859ba-df79-408c-a639-84bf2559ce16_68328.jpg",
            locality:
              "First Floor, Shaikpet Village, beside Thick shake factory",
            areaName: "Shaikpet",
            costForTwo: "₹400 for two",
            cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
            avgRating: 4.7,
            parentId: "3534",
            avgRatingString: "4.7",
            totalRatingsString: "8.8K+",
          },
        },
        {
          info: {
            id: "68332",
            name: "LunchBox - Meals and Thalis",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2024/10/16/76bd7908-6d49-40f5-a0f0-759080dd7daa_68332=.jpg",
            locality:
              "First Floor, Shaikpet Village, beside Thick shake factory",
            areaName: "Shaikpet",
            costForTwo: "₹200 for two",
            cuisines: [
              "Thalis",
              "North Indian",
              "Biryani",
              "South Indian",
              "Desserts",
              "Beverages",
            ],
            avgRating: 4.2,
            parentId: "4925",
            avgRatingString: "4.2",
            totalRatingsString: "10K+",
          },
        },
        {
          info: {
            id: "18785",
            name: "Cafe Coffee Day",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2025/8/21/4ce445d9-aefe-495b-8220-5eb0e8fe4777_18785.JPG",
            locality: "Tolichowki",
            areaName: "Tolichowki",
            costForTwo: "₹400 for two",
            cuisines: [
              "Beverages",
              "Cafe",
              "Snacks",
              "Desserts",
              "Burgers",
              "Ice Cream",
              "Bakery",
              "Fast Food",
            ],
            avgRating: 4.3,
            parentId: "1",
            avgRatingString: "4.3",
            totalRatingsString: "6.3K+",
          },
        },
        {
          info: {
            id: "347774",
            name: "Varalakshmi Tiffins",
            cloudinaryImageId:
              "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/11/c75ff48c-b373-4733-8126-e3180cbb0fa0_347774.jpg",
            locality: "Manikonda",
            areaName: "Narsingi",
            costForTwo: "₹300 for two",
            cuisines: ["South Indian"],
            avgRating: 4.5,
            veg: true,
            parentId: "6482",
            avgRatingString: "4.5",
            totalRatingsString: "35K+",
          },
        },
        {
          info: {
            id: "54552",
            name: "The Thick Shake Factory",
            cloudinaryImageId: "v0f58qb96jw4y1ftomoo",
            locality: "OU colony",
            areaName: "Manikonda",
            costForTwo: "₹200 for two",
            cuisines: ["Beverages", "American"],
            avgRating: 3.9,
            parentId: "1033",
            avgRatingString: "3.9",
            totalRatingsString: "11K+",
          },
          collectionId: "84124",
        },
    
  ];